Prevent walking through walls and allow walking sideways
AdRoll/rustenstein pull request #23
Opened 2022-03-19 18:41 UTC by PavelVavruska

Implementation of player's collision with walls. Player slides on walls and never gets stuck. Additionally the support of two directional movement was implemented [holding two keys: forward + step_sideways (key "," and ".")].

### Implementation details:
Based on player's movement angle three vertices of player's collision box (square) are checked after the movement is requested by pressing keyboard keys. These three vertices are converted into map coordinates. 

```
 ■ - player angle (first vertex), ╬ - checked collision vertex of player's box, o - player core position
         ■─╬
         │o│
         ╬─┘
```

If any of those coordinates contains a wall, movement is restricted by sliding (one axis restriction, e.g. walking into middle of long wall at angle <> 90°) or movement stop (two axis restriction, e.g. walking into corner).

2022-03-21 00:42 UTC, facundoolano requested changes
Thanks for contributing! left some comments

2022-03-21 00:42 UTC, facundoolano commented on src/main.rs
> +    let mut is_moving_sidaways = false;
```suggestion
    let mut is_moving_sideways = false;
```

2022-03-21 00:42 UTC, facundoolano commented on src/main.rs
> +        player.move_angle = player.view_angle;
is there any chance you can rearrange this code in a similar style as before, checking input here and having player internals (view and move angle changes) managed in the player module?

2022-03-21 00:42 UTC, facundoolano commented on src/player.rs
> +    pub fn move_player(&mut self, map: &map::Map) {
```suggestion
    pub fn move(&mut self, map: &map::Map) {
```

the player suffix is redundant in a player struct method

2022-03-22 19:10 UTC, PavelVavruska commented on src/main.rs
> +    let mut is_moving_sidaways = false;
Good catch, fixed in latest commit revision cee80e28ba6ae7588d6c8b6c5ef1d47295868f7a.
Thank you.

2022-03-22 19:11 UTC, PavelVavruska commented on src/main.rs
> +        player.move_angle = player.view_angle;
Good point, moved in latest commit revision cee80e28ba6ae7588d6c8b6c5ef1d47295868f7a.
Thank you.

2022-03-22 19:12 UTC, PavelVavruska commented on src/player.rs
> +    pub fn move_player(&mut self, map: &map::Map) {
I agree, but method name "move" is illegal in Rust so I renamed it to "walk" in latest commit revision cee80e28ba6ae7588d6c8b6c5ef1d47295868f7a.
Thank you.

2022-03-23 23:29 UTC, facundoolano approved these changes

2022-03-23 23:29 UTC, facundoolano commented on src/main.rs
> +    player.start_walk(map);
I think there's further room for improvement for this API. The set_walk_x and start_walk methods are inter-dependent, and they force you to add the is_moving flags to the player struct just to be used right away in the other method. 

I'm thinking in an API like this

```rust
enum FrontMovement {
    Forward,
    Backward
}

enum SideMovement {
    TurnRight,
    TurnLeft,
    StrafeRight,
    StrafeLeft,
}

impl Player {
    // ...

    fn walk(&mut self, map: &map::Map, front: Option<FrontMovement>, side: Option<SideMovement>, run: bool) {
        // ...
    }
}
```

This way the player api is composed of those two enums plus one movement method, vs the multiple small interdependent ones we have now. And the input parsing becomes more closely separated from the player, you translate input keys into directions and then tell the players what direction to move, without having to track pressed keys internally.

2022-03-23 23:29 UTC, facundoolano commented on src/main.rs
> +    player.start_walk(map);
_of course_ this is being nit-picky, don't feel obligated to implement this, we can do it after merging this PR if you prefer

2022-03-25 13:14 UTC, juanbono approved these changes

2022-03-28 20:47 UTC, PavelVavruska commented on src/main.rs
> +    if window.is_key_down(Key::Comma) {
I agree with keeping the keyboard layout close to original. Revision 6dbaadef78af300549baa9dc9cf1a5020c90bc43 introduces usage of ALT key for alternating between strafing and turning. I also extended the key layout with current style of movement (WASD) as it will help younger players and might overall make the experience easier for future debugging. Running with SHIFT key was added as well.

2022-03-28 21:05 UTC, PavelVavruska commented on src/main.rs
> +    player.start_walk(map);
Thank you for suggestion. I implemented it (revision 6dbaadef78af300549baa9dc9cf1a5020c90bc43) with a slight change: I kept turning movement and side movement separate as they are two different types of movement. Current implementation enables, for example, strafing left and turning left at the same time.

```rust
pub enum StraightMovement {
    Forward,
    Backward,
}

pub enum SideMovement {
    StrafeRight,
    StrafeLeft,
}

pub enum TurnMovement {
    TurnRight,
    TurnLeft,
}

// ...

impl Player {
    /// ...
    pub fn walk(
        &mut self,
        map: &map::Map,
        straight: Option<StraightMovement>,
        side: Option<SideMovement>,
        turn: Option<TurnMovement>,
        run: bool,
    )

```

2022-03-29 18:51 UTC, facundoolano commented
@PavelVavruska the code looks great now. But I see a couple of problems when running the game (I'm running as `cargo run --release` btw):

- turn speed is way too fast in my machine 
- alt + arrow doesn't seem to strafe in my external keyboard (may be some issue with my local setup though). 
- in the laptop keyboard, strafe seems to work
- both in laptop and external keyboard, if I run cmd + left or right key, the camera starts spinning like crazy

2022-03-29 19:44 UTC, PavelVavruska commented
@facundoolano Does the camera stop spinning after few seconds? (longer the press of key = longer the spinning)? If yes, my guess is that someone added buffering of user key input and the engine is unable to keep up. It wasn't happening when I was working on this pull request: https://github.com/AdRoll/rustenstein/pull/15 Or the engine is now overall slower.

I am running Manjaro linux in VM (Ryzen 5600X desktop with fullsize keyboard) and I am also experiencing some performance issues (e.g. while holding turn key for longer than few seconds the game fills some buffer and is not able to execute the movement in real time. That causes the camera to keep moving few seconds after the key is released.) I believe this "bug" was introduced in the last month and is not directly related to this pull request. 

I just retested the strafing with the ALT key and it works well on my machine. You can also use keys Q and E to strafe directly.

2022-03-31 17:07 UTC, PavelVavruska commented
@facundoolano Thank you for the bug report. I have successfully reproduced the error that left ALT key is not working and the right ALT key causes the player to spin infinitely and can be stopped only by pressing the right ALT key again.

Also my "slow buffer" bug described by me in my last post does not appear on native W10 machine and is probably just WM issue.

Reproduced on: Windows 10 version 21H1, Ryzen 5600X, 32 GB RAM.

I am working on the fix.

2022-04-07 07:45 UTC, PavelVavruska commented
Requesting merge of this pull request. Thank you.

2022-04-07 22:58 UTC, merged

2022-04-07 22:58 UTC, facundoolano commented
Thanks for the contribution!